FROM node:14-alpine

RUN apk add --no-cache bash git yarn openjdk8-jre python python3 build-base linux-headers eudev-dev cups-dev
RUN npm -g install lerna firebase-tools
RUN firebase setup:emulators:firestore
